Upgrade auth menu, add normal exit option. Start create user menu.
ElQelinho/ATMproject pull request #6
Opened 2022-12-23 17:55 UTC by ElQelinho

2022-12-23 18:30 UTC, ayrapetovai requested changes

2022-12-23 18:30 UTC, ayrapetovai commented on src/main/java/com/example/menu/Auth.java
> +            return new Error(errorMessage, () -> new Auth());
errorMessage пустая строка, нужно хоть что-нибудь передать. Можно взять описание ошибки из errorMessage.getMessage()

2022-12-23 18:30 UTC, ayrapetovai commented on src/main/java/com/example/menu/Auth.java
> +            return new Error(errorMessage, () -> new Auth());
errorMessage пустая строка, нужно хоть что-нибудь передать. Можно взять описание ошибки из errorMessage.getMessage()

2022-12-23 18:30 UTC, ayrapetovai commented on src/main/java/com/example/menu/Auth.java
> +                return new Error(errorMessage, () -> new Auth());
errorMessage пустая строка, нужно хоть что-нибудь передать. Можно взять описание ошибки из errorMessage.getMessage()

2022-12-23 18:30 UTC, ayrapetovai commented on src/main/java/com/example/menu/Auth.java
> +            if (exitChoose.equals("y")) {
NullPointerException в месте вызова equals, если ввод прервался выбросом исключения. Использовать equals в стиле "null safe": "y".equals(exitChoose)

2022-12-23 18:30 UTC, ayrapetovai commented on src/main/java/com/example/menu/Auth.java
> +            } else if (exitChoose.equals("N")){
NullPointerException в месте вызова equals, если ввод прервался выбросом исключения. Использовать equals в стиле "null safe": "N".equals(exitChoose)

2022-12-23 18:30 UTC, ayrapetovai commented on src/main/java/com/example/menu/Auth.java
> +                return new Exit();
Почему выходим, может быть нужно вернуться в главное меню?

2022-12-23 18:30 UTC, ayrapetovai commented on src/main/java/com/example/menu/Auth.java
> +                return new Error(errorMessage, () -> new Auth());
При такой обработке ошибки ввода, пользователю будет снова предложено ввести номер карты и пин. Лучше сделать ввод пользователя в цикле и выходить, если ввод корректный или после (например) 5 попыток.

2022-12-23 18:30 UTC, ayrapetovai commented on src/main/java/com/example/menu/UserMenu.java
> +    BufferedReader enterReader = new BufferedReader(new InputStreamReader(System.in));
Объявление поля данных после объявления конструктора не соответствует Java Code Conventions. Нужно объявлять все поля до (выше) методов/конструкторов. К тому же, в другом меню поле с ридером не объявлено, вместо этого он создан в методе processMenu, надо привести к единому подходу (может быть любому, но я бы все делал в методе processMenu).

2022-12-23 18:30 UTC, ayrapetovai commented on src/main/java/com/example/menu/UserMenu.java
> +    Account userAccount;
Это поле должно быть private final, потому, что мы не хотим чтобы оно менялось после авторизации, и не было доступно "другим" классам.

2022-12-23 18:30 UTC, ayrapetovai commented on src/main/java/com/example/menu/UserMenu.java
> +            return new Error(errorMessage, () -> new UserMenu(null));
errorMessage пустая строка, нужно хоть что-нибудь передать. Можно взять описание ошибки из errorMessage.getMessage()

2022-12-23 18:30 UTC, ayrapetovai commented on src/main/java/com/example/menu/UserMenu.java
> +            case 5:
Лучше сделать ветку deafult которая бы сигнализировала пользователю об ошибке путем возвращения состояния Error, или считывать ввод пользователя в цикле до тех пор, пока он не введен правильный номер или не более 5 раз.

2022-12-23 18:30 UTC, ayrapetovai commented on src/main/java/com/example/menu/UserMenu.java
> +                System.out.println("Your balanse is $" + userAccount.getBalance());
Может быть, после выполнении этого пункта пользователь снова должен попадать в это же меню, `return new UserMenu(..)`?

2022-12-23 18:30 UTC, ayrapetovai commented on src/main/java/com/example/menu/UserMenu.java
> +        return new Exit();
Этот `return new Exit();` - костыль, из-за отсутствия обработки ошибки ввода пользователя.

2022-12-23 18:30 UTC, ayrapetovai commented on src/main/java/com/example/menu/UserMenu.java
> +        System.out.println("5.Exit");
Может быть не "Exit", а "Back" для перехода в предыдущее или главное меню?

2023-01-07 11:00 UTC, ElQelinho commented on src/main/java/com/example/menu/Auth.java
> +            return new Error(errorMessage, () -> new Auth());
Fixed

2023-01-07 11:01 UTC, ElQelinho commented on src/main/java/com/example/menu/Auth.java
> +                return new Error(errorMessage, () -> new Auth());
Fixed

2023-01-07 11:01 UTC, ElQelinho commented on src/main/java/com/example/menu/Auth.java
> +                return new Exit();
Fixed

2023-01-07 11:01 UTC, ElQelinho commented on src/main/java/com/example/menu/Auth.java
> +                return new Error(errorMessage, () -> new Auth());
Fixed

2023-01-07 11:01 UTC, ElQelinho commented on src/main/java/com/example/menu/UserMenu.java
> +    BufferedReader enterReader = new BufferedReader(new InputStreamReader(System.in));
Fixed

2023-01-07 11:01 UTC, ElQelinho commented on src/main/java/com/example/menu/UserMenu.java
> +    Account userAccount;
Fixed

2023-01-07 11:01 UTC, ElQelinho commented on src/main/java/com/example/menu/UserMenu.java
> +            return new Error(errorMessage, () -> new UserMenu(null));
Fixed

2023-01-07 11:01 UTC, ElQelinho commented on src/main/java/com/example/menu/UserMenu.java
> +            case 5:
Fixed

2023-01-07 11:01 UTC, ElQelinho commented on src/main/java/com/example/menu/UserMenu.java
> +                System.out.println("Your balanse is $" + userAccount.getBalance());
Fixed

2023-01-07 11:01 UTC, ElQelinho commented on src/main/java/com/example/menu/UserMenu.java
> +        return new Exit();
Не костыль, а заглушка

2023-01-07 11:02 UTC, ElQelinho commented on src/main/java/com/example/menu/UserMenu.java
> +        System.out.println("5.Exit");
Fixed

2023-01-08 11:51 UTC, merged