Ended Menu.
ElQelinho/ATMproject pull request #8
Opened 2023-01-23 17:21 UTC by ElQelinho

2023-01-27 19:20 UTC, ayrapetovai requested changes

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/ATM.java
> +        returnContext = bank.incomeBalance(income, userContext);
Банк не должен ничего знать о `userContext`, потому, что это часть меню, а не банка. Нужно заменить параметр функции `incomeBalance` `userContext` на номер счета и пин.

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/ATM.java
> +    public MenuContext stealBalance(BigDecimal steal, MenuContext userContext) {
Банк не должен ничего знать о `userContext`, потому, что это часть меню, а не банка. Нужно заменить параметр функции `stealBalance` `userContext` на номер счета.

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/ATM.java
> +    public MenuContext transferBalance(int cardNumber, BigDecimal money,MenuContext userContext) {
Тоже самое, банк не должен знать о части меню банкомата.

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/Bank.java
> +    Account clientAccount;
Поля newBalance, clientBalance, menuContext, userAccount, clientAccount не являются состоянием банка, они мог быть частью какой-то его операции. Но не частью банка они не являются. У банка нет никакого уникального newBalance для какого-то одного клиента, например так можно рассуждать. У банка есть список заведенных счетов.

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/Bank.java
>      private ArrayList<Account> createAccount(String firstUserName, String secondUserName, int cardNum, byte pin) {
cardNum не может быть входным параметром для создания счета. Если он есть среди параметров операции создания счета, то это звучит как "Банк, создай мне счет вот с таким номером", это не правильно, банк сам ведет счета, сам определяет какой номер счета создать для счета.

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/ATM.java
>      public boolean validateUser(Account autorizedUser) {
Как это "Account autorizedUser", либо аккаунт либо клиент. Имя переменной странное.

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/Bank.java
> +    public MenuContext incomeBalance(BigDecimal income, MenuContext userContext) {
Та же ерунда, про то, что банк ничего не должен знать ни о каком меню, заменить параметр userContext на другой, более логмчный (сумма, пин)

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/Bank.java
> +        menuContext.setAccount(userAccount);
Возвращать результат операции. А не "Объект в котором пришли данные для операции".

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/Bank.java
> +        if (newBalance.compareTo(steal) == -1) {
Контракт Comparable не разрешает сравнивать результат сравнивания с конкретными числами, кроме нуля.
Должно быть: `newBalance.compareTo(steal) < 0`, потому, что некоторые алгоритмы сравнивания могут просто возвращать, например, результат вычитания длины одного массива из длины другого массива.

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/Bank.java
> +    public MenuContext stealBalance(BigDecimal steal, MenuContext userContext) {
Опять же банк не должен ничего знать о MenuContext.

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/Bank.java
> +        return menuContext;
Надо возвращать результат операции, а не запрос.
Например:
```java
class OperationResult {
    BigDecimal prevBalance = ...;
    BigDecimal newBalance = ...;
}
```

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/Bank.java
> +    public MenuContext transferAccount(int cardNumber,BigDecimal money,MenuContext userContext) {
userContext не передавать в банк

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/Bank.java
> +        menuContext = userContext;
Запрос на изменение состояние счета не должен менять банк. Не изменять состояние банка - поля данных в методах-операциях-над-счетом.

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/Bank.java
> +            if ((acc.getCardNum() == cardNumber)) {
Лишние скобки ()

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/Bank.java
> +        if (newBalance.compareTo(money) == -1) {
Аналогично предыдущему по контракту Comparable:
`if (newBalance.compareTo(money) < 0)`

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/Bank.java
> +            System.out.println("Operation denied, low balance");
Логировать сколько было денег на счету, на каком, сколько нужно было снять.

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/Bank.java
> +        System.out.println("Transfer complete!");
Тут тоже логировать еще информации.

2023-01-27 19:20 UTC, ayrapetovai commented on src/main/java/com/example/Bank.java
> +        return menuContext;
Возвращать объект специального класса, который заведен специально для результата операции.

2023-02-01 16:14 UTC, ElQelinho commented on src/main/java/com/example/ATM.java
> +        returnContext = bank.incomeBalance(income, userContext);
Fixed.

2023-02-01 16:14 UTC, ElQelinho commented on src/main/java/com/example/ATM.java
> +    public MenuContext stealBalance(BigDecimal steal, MenuContext userContext) {
Fixed

2023-02-01 16:14 UTC, ElQelinho commented on src/main/java/com/example/ATM.java
> +    public MenuContext transferBalance(int cardNumber, BigDecimal money,MenuContext userContext) {
Fixed

2023-02-01 16:14 UTC, ElQelinho commented on src/main/java/com/example/Bank.java
> +    Account clientAccount;
Fixed. Поля убраны.

2023-02-01 16:15 UTC, ElQelinho commented on src/main/java/com/example/Bank.java
> +            if ((acc.getCardNum() == cardNumber)) {
Fixed.

2023-02-01 16:16 UTC, ElQelinho commented on src/main/java/com/example/Bank.java
> +        if (newBalance.compareTo(money) == -1) {
Fixed

2023-02-01 16:16 UTC, ElQelinho commented on src/main/java/com/example/Bank.java
> +            if ((acc.getCardNum() == cardNumber)) {
Fixed

2023-02-01 16:17 UTC, ElQelinho commented on src/main/java/com/example/Bank.java
> +    public MenuContext incomeBalance(BigDecimal income, MenuContext userContext) {
Fixed

2023-02-01 16:17 UTC, ElQelinho commented on src/main/java/com/example/Bank.java
> +        menuContext.setAccount(userAccount);
Fixed

2023-02-01 16:17 UTC, ElQelinho commented on src/main/java/com/example/Bank.java
> +        if (newBalance.compareTo(steal) == -1) {
Fixed

2023-02-01 16:18 UTC, ElQelinho commented on src/main/java/com/example/Bank.java
> +    public MenuContext stealBalance(BigDecimal steal, MenuContext userContext) {
Fixed

2023-02-01 16:18 UTC, ElQelinho commented on src/main/java/com/example/Bank.java
> +        return menuContext;
Fixed

2023-02-01 16:18 UTC, ElQelinho commented on src/main/java/com/example/Bank.java
> +    public MenuContext transferAccount(int cardNumber,BigDecimal money,MenuContext userContext) {
Fixed

2023-02-01 16:18 UTC, ElQelinho commented on src/main/java/com/example/Bank.java
> +        menuContext = userContext;
Fixed

2023-02-01 16:19 UTC, ElQelinho commented on src/main/java/com/example/ATM.java
> +        returnContext = bank.incomeBalance(income, userContext);
Fixed

2023-02-01 16:25 UTC, ElQelinho commented on src/main/java/com/example/ATM.java
>      public boolean validateUser(Account autorizedUser) {
Fixed

2023-02-01 16:30 UTC, ElQelinho commented on src/main/java/com/example/Bank.java
>      private ArrayList<Account> createAccount(String firstUserName, String secondUserName, int cardNum, byte pin) {
Это выглядит как менеджер в банке создает счет с стаким-то номером. Нужно для облегчения дебага, так как есть я буду создавать счет рандомно, нужно будет создавать метод, для проявления счета и пина, что бы тестить. А это накладно.

2023-02-01 16:48 UTC, ayrapetovai commented on src/main/java/com/example/Bank.java
>      private ArrayList<Account> createAccount(String firstUserName, String secondUserName, int cardNum, byte pin) {
Менеджер не знает номера счета до того, как система его создавать :)

2023-02-06 17:43 UTC, merged